title: DATAMIND Catalogue
description: A curated catalogue of data resources, software and data pipelines for mental health research.
url: "https://roblinksdata.github.io"
baseurl: "/DATAMIND-catalogue"
github_repo_url: "https://github.com/roblinksdata/DATAMIND-catalogue/"
catalogue_issue_path: "issues/new?template=catalogue-change.yml"
repository: roblinksdata/DATAMIND-catalogue
datamind_github_org_url: "https://github.com/DATAMIND-UK/"
markdown: kramdown
permalink: pretty
collections:
  data-resources:
    output: true
    permalink: /data-resources/:name/
  software:
    output: true
    permalink: /software/:name/
  data-pipelines:
    output: true
    permalink: /data-pipelines/:name/
defaults:
  - scope:
      path: ""
      type: data_resources
    values:
      layout: catalogue-entry
      category: Data resources
  - scope:
      path: ""
      type: software
    values:
      layout: catalogue-entry
      category: Software
  - scope:
      path: ""
      type: data_pipelines
    values:
      layout: catalogue-entry
      category: Data pipelines
exclude:
  - README.md
  - CONTRIBUTING.md
  - scripts
  - vendor
